#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App.Apresentacao.Resource", IsApplication=true)]

namespace App.Apresentacao
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int LogoMobile = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int LogoProdutoMobile = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int LogoProdutoMobile1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int LogosMobile = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int SemTitulo111 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Splash = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000f
			public const int btnAgendar = 2131099663;
			
			// aapt resource value: 0x7f06003b
			public const int btnCadastrar = 2131099707;
			
			// aapt resource value: 0x7f060018
			public const int btnConcluir = 2131099672;
			
			// aapt resource value: 0x7f060041
			public const int btnMySql = 2131099713;
			
			// aapt resource value: 0x7f060049
			public const int btnNull = 2131099721;
			
			// aapt resource value: 0x7f060046
			public const int btnagendamento = 2131099718;
			
			// aapt resource value: 0x7f060048
			public const int btninformacoes = 2131099720;
			
			// aapt resource value: 0x7f060043
			public const int btnlogin = 2131099715;
			
			// aapt resource value: 0x7f060047
			public const int btnservico = 2131099719;
			
			// aapt resource value: 0x7f060021
			public const int datePicker1 = 2131099681;
			
			// aapt resource value: 0x7f060010
			public const int imageView1 = 2131099664;
			
			// aapt resource value: 0x7f060000
			public const int imageView2 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int lblAgende = 2131099649;
			
			// aapt resource value: 0x7f06002c
			public const int lblBairro = 2131099692;
			
			// aapt resource value: 0x7f060024
			public const int lblCEP = 2131099684;
			
			// aapt resource value: 0x7f06001e
			public const int lblCPF = 2131099678;
			
			// aapt resource value: 0x7f060015
			public const int lblCPFEsq = 2131099669;
			
			// aapt resource value: 0x7f06002e
			public const int lblCidade = 2131099694;
			
			// aapt resource value: 0x7f060002
			public const int lblCliente = 2131099650;
			
			// aapt resource value: 0x7f06002a
			public const int lblCompl = 2131099690;
			
			// aapt resource value: 0x7f060034
			public const int lblDDD = 2131099700;
			
			// aapt resource value: 0x7f060020
			public const int lblData = 2131099680;
			
			// aapt resource value: 0x7f060006
			public const int lblDuracao = 2131099654;
			
			// aapt resource value: 0x7f060022
			public const int lblEmail = 2131099682;
			
			// aapt resource value: 0x7f060011
			public const int lblEmailEsq = 2131099665;
			
			// aapt resource value: 0x7f060026
			public const int lblEnde = 2131099686;
			
			// aapt resource value: 0x7f060044
			public const int lblEscSenh = 2131099716;
			
			// aapt resource value: 0x7f06000a
			public const int lblHorario = 2131099658;
			
			// aapt resource value: 0x7f06001a
			public const int lblNome = 2131099674;
			
			// aapt resource value: 0x7f060013
			public const int lblNomeCom = 2131099667;
			
			// aapt resource value: 0x7f06003c
			public const int lblNovSen = 2131099708;
			
			// aapt resource value: 0x7f060028
			public const int lblNumero = 2131099688;
			
			// aapt resource value: 0x7f06000c
			public const int lblObs = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int lblProf = 2131099656;
			
			// aapt resource value: 0x7f06001c
			public const int lblRG = 2131099676;
			
			// aapt resource value: 0x7f060045
			public const int lblRegist = 2131099717;
			
			// aapt resource value: 0x7f060019
			public const int lblRegistre = 2131099673;
			
			// aapt resource value: 0x7f06003e
			public const int lblRepSen = 2131099710;
			
			// aapt resource value: 0x7f060038
			public const int lblSenha = 2131099704;
			
			// aapt resource value: 0x7f060004
			public const int lblServicos = 2131099652;
			
			// aapt resource value: 0x7f060032
			public const int lblTTele = 2131099698;
			
			// aapt resource value: 0x7f060036
			public const int lblTelefone = 2131099702;
			
			// aapt resource value: 0x7f060030
			public const int lblUF = 2131099696;
			
			// aapt resource value: 0x7f060042
			public const int linearLayout1 = 2131099714;
			
			// aapt resource value: 0x7f06003a
			public const int linearLayout2 = 2131099706;
			
			// aapt resource value: 0x7f06000e
			public const int linearLayout3 = 2131099662;
			
			// aapt resource value: 0x7f060017
			public const int linearLayout4 = 2131099671;
			
			// aapt resource value: 0x7f060040
			public const int lvDados = 2131099712;
			
			// aapt resource value: 0x7f060033
			public const int spnTTele = 2131099699;
			
			// aapt resource value: 0x7f060031
			public const int spnUF = 2131099697;
			
			// aapt resource value: 0x7f06002d
			public const int txtboxBairro = 2131099693;
			
			// aapt resource value: 0x7f060025
			public const int txtboxCEP = 2131099685;
			
			// aapt resource value: 0x7f06001f
			public const int txtboxCPF = 2131099679;
			
			// aapt resource value: 0x7f060016
			public const int txtboxCPFEsq = 2131099670;
			
			// aapt resource value: 0x7f06002f
			public const int txtboxCidade = 2131099695;
			
			// aapt resource value: 0x7f060003
			public const int txtboxCliente = 2131099651;
			
			// aapt resource value: 0x7f06002b
			public const int txtboxCompl = 2131099691;
			
			// aapt resource value: 0x7f060035
			public const int txtboxDDD = 2131099701;
			
			// aapt resource value: 0x7f060007
			public const int txtboxDuracao = 2131099655;
			
			// aapt resource value: 0x7f060023
			public const int txtboxEmail = 2131099683;
			
			// aapt resource value: 0x7f060012
			public const int txtboxEmailEsq = 2131099666;
			
			// aapt resource value: 0x7f060027
			public const int txtboxEnde = 2131099687;
			
			// aapt resource value: 0x7f06000b
			public const int txtboxHorario = 2131099659;
			
			// aapt resource value: 0x7f06001b
			public const int txtboxNome = 2131099675;
			
			// aapt resource value: 0x7f060014
			public const int txtboxNomeCom = 2131099668;
			
			// aapt resource value: 0x7f06003d
			public const int txtboxNovSen = 2131099709;
			
			// aapt resource value: 0x7f060029
			public const int txtboxNumero = 2131099689;
			
			// aapt resource value: 0x7f06000d
			public const int txtboxObs = 2131099661;
			
			// aapt resource value: 0x7f060009
			public const int txtboxProf = 2131099657;
			
			// aapt resource value: 0x7f06001d
			public const int txtboxRG = 2131099677;
			
			// aapt resource value: 0x7f06003f
			public const int txtboxRepSen = 2131099711;
			
			// aapt resource value: 0x7f060039
			public const int txtboxSenha = 2131099705;
			
			// aapt resource value: 0x7f060005
			public const int txtboxServicos = 2131099653;
			
			// aapt resource value: 0x7f060037
			public const int txtboxTelefone = 2131099703;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Agendamento = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AuteEsqSenha = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CadCliente = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EsqueceuSenha = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int layout1 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Login = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Menu = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040002
			public const int CadCliente_Theme = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Login_Theme = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int SplashScreen_Theme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
